#!/bin/sh
### BEGIN INIT INFO
# Provides:          ngrok
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the ngrok Proxy => /etc/init.d/ngrok.
### END INIT INFO


ngrok_path=/root/ngrok
case "$1" in
        start)
                echo "start ngrok ssh service.."
                sh ${ngrok_path}/ngrok-ssh.sh
                ;;
        *)
        exit 1
        ;;
esac