#!/bin/sh
### BEGIN INIT INFO
# Provides:          ngrok
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the ngrok Proxy => /etc/init.d/ngrok.
### END INIT INFO


ngrok_path=/root/ngrok
start()
{
        echo "start ngrok ssh service.."
        pkill ngrok
        sh ${ngrok_path}/ngrok-ssh.sh
        exit 0;
}
stop()
{
        pkill ngrok
        echo "stop ngrok service..."
}
case "$1" in
        start)
                start   
                ;;
        stop)
                stop
                ;;
        restart|reload)
                stop
                start
                ;;
        *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 0
        ;;
esac

exit 0